# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Wang
author: Michael Wang
email: cwang.michael.23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://morningfin.github.io" # the base hostname & protocol for your site
github_username:  morningfin
permalink: pretty

# Build settings
markdown: kramdown
exclude: [jekyll.sublime-project, jekyll.sublime-workspace, README.md]
